matrix:
  include:
    - os: linux
      sudo: required
      env: TARGET_CPU=x64
      addons:
        apt: &x64-apt
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - libglib2.0-dev
          - libgtk2.0-dev
          - libgtk-3-dev
          - libxtst-dev
          - libxss-dev
          - libpci-dev
          - libdbus-1-dev
          - libgconf2-dev
          - libgnome-keyring-dev
          - libnss3-dev
          - libasound2-dev
          - libpulse-dev
          - libudev-dev

    - os: linux
      sudo: required
      env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug
      addons:
        apt: *x64-apt

    - os: osx
      osx_image: xcode8.3
      env: TARGET_CPU=x64
      addons:
        apt: *x64-apt

    - os: osx
      osx_image: xcode8.3
      env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug
      addons:
        apt: *x64-apt

language: cpp

before_install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  else
    if ! brew ls --version cmake &>/dev/null; then brew update && brew install cmake; fi
  fi
- cd ${TRAVIS_BUILD_DIR}
- cmake --version

install:
- git submodule init
- git submodule update
- mkdir out
- cd out
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=. -DTARGET_CPU=$TARGET_CPU ..

script:
- make -j 4 package

before_deploy:
  - export TRAVIS_ARTIFACTS=$(ls libwebrtc-*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: nCUOIKK2U/dKQEfo3iNSwiMenw+PKVWn+0uDPYxmYjvAY9GRXwyENORlTb62DMcme0W7NZthYieQfU94NTE3vcEaF1ERWhFxTfQ6pI4XmqyzhzPNgS4vzYp80NodkRDDRi1sI8OFTX3PlAzXILMGUOtwiFZ+9bcXXc8+toaCG+gHQ4sCnSLWPt6AQWCQXRKfhFtBrg7KC1rcBPel+zy1VCKEhwphWxHWZRhGjO8FjDfqima0qSbF8eEjBQtEubGG50QIG9o6qAfJcqqVme8Kt83zPvCuMKWy1I25NMun9KEGuiJs2lq5PnX6BvReyuilGVLaQKHynz2viwyYwBJrynmYxxOFhu5WV03DTcIal777Hqlkh02SSVrkyCNhkzD3p9Xm/9QIrnzGlg+ND/jOkKgfC6PHTZ6Gw07zxRULgsaF2FhpQdUgI/0U8jrMHuYH5RcvS1M+78gZfTUasaMgg4a7zMD1ljfHVtfM/N8Kyocw0BEGsKsunPh7DxXG0UKcntJl0LKc+oUgEVtndKQ/M2eu/HqeKJekNfEeprST+2x6+97dpHGh20VrsNIUCQATcDDyWY3BwGXuSuDBGsdQD6qMHgXBCPcPaGQeyIlxsjnjhSOSoocl9TAMa6mj3Lgej01WCblg62OuHYK/xFgTWc6UnmLvHwjKkwcDfNddXXc=
  file_glob: true
  file: "${TRAVIS_ARTIFACTS}"
  skip_cleanup: true
  on:
    tags: true
    repo: markandrus/libwebrtc
    branch: node-webrtc
